// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_collection from "./routes/api/collection.tsx";
import * as $api_document from "./routes/api/document.tsx";
import * as $api_productsInfos from "./routes/api/productsInfos.tsx";
import * as $utils_apiFetch from "./routes/utils/_apiFetch.ts";
import * as $utils_constant from "./routes/utils/_constant.ts";
import * as $Filters from "./islands/Filters.tsx";
import * as $FooterNewsletter from "./islands/FooterNewsletter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/collection.tsx": $api_collection,
    "./routes/api/document.tsx": $api_document,
    "./routes/api/productsInfos.tsx": $api_productsInfos,
    "./routes/utils/_apiFetch.ts": $utils_apiFetch,
    "./routes/utils/_constant.ts": $utils_constant,
  },
  islands: {
    "./islands/Filters.tsx": $Filters,
    "./islands/FooterNewsletter.tsx": $FooterNewsletter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
