// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/minicart/submit.ts";
import * as $$$$$$$$$1 from "./actions/newsletter/subscribe.ts";
import * as $$$$$$$$$2 from "./actions/wishlist/submit.ts";
import * as $$$$$$$$$$$0 from "./apps/blog/islands/BackButton.tsx";
import * as $$$$$$$$$$$1 from "./apps/blog/loaders/Author.ts";
import * as $$$$$$$$$$$5 from "./apps/blog/loaders/Blogpost.ts";
import * as $$$$$$$$$$$2 from "./apps/blog/loaders/BlogPostItem.ts";
import * as $$$$$$$$$$$6 from "./apps/blog/loaders/BlogpostList.ts";
import * as $$$$$$$$$$$7 from "./apps/blog/loaders/BlogpostListing.ts";
import * as $$$$$$$$$$$3 from "./apps/blog/loaders/BlogPostPage.ts";
import * as $$$$$$$$$$$4 from "./apps/blog/loaders/BlogRelatedPosts.ts";
import * as $$$$$$$$$$$8 from "./apps/blog/loaders/Category.ts";
import * as $$$$$$$$$$$9 from "./apps/blog/loaders/ContentTypes.ts";
import * as $$$$$$$$$$$10 from "./apps/blog/loaders/GetCategories.ts";
import * as $$$$$$$$$$$11 from "./apps/blog/manifest.gen.ts";
import * as $$$$$$$$$$$12 from "./apps/blog/mod.ts";
import * as $$$$$$$$$$$13 from "./apps/blog/sections/Blog/components/ImageAndTextSection.tsx";
import * as $$$$$$$$$$$16 from "./apps/blog/sections/Blog/components/ImagesSlide.tsx";
import * as $$$$$$$$$$$14 from "./apps/blog/sections/Blog/components/ImageThreeColumnSection.tsx";
import * as $$$$$$$$$$$15 from "./apps/blog/sections/Blog/components/ImageTwoColumnSection.tsx";
import * as $$$$$$$$$$$17 from "./apps/blog/sections/Blog/components/OneImage.tsx";
import * as $$$$$$$$$$$18 from "./apps/blog/sections/Blog/components/ProductsSection.tsx";
import * as $$$$$$$$$$$19 from "./apps/blog/sections/Blog/components/RelatedPosts.tsx";
import * as $$$$$$$$$$$20 from "./apps/blog/sections/Blog/components/TextSection.tsx";
import * as $$$$$$$$$$$21 from "./apps/blog/sections/Blog/components/Video.tsx";
import * as $$$$$$$$$$$22 from "./apps/blog/sections/BlogBannerPost.tsx";
import * as $$$$$$$$$$$23 from "./apps/blog/sections/BlogPosts.tsx";
import * as $$$$$$$$$$$24 from "./apps/blog/sections/BlogTemplate.tsx";
import * as $$$$$$$$$$$25 from "./apps/blog/sections/Seo/SeoBlogPost.tsx";
import * as $$$$$$$$$$$26 from "./apps/blog/sections/Seo/SeoBlogPostListing.tsx";
import * as $$$$$$$$$$$27 from "./apps/blog/sections/Template.tsx";
import * as $$$$$$$$$$$28 from "./apps/blog/sections/types.ts";
import * as $$$$$$$$$$$31 from "./apps/blog/utils/clx.ts";
import * as $$$$$$$$$$$32 from "./apps/blog/utils/constants.ts";
import * as $$$$$$$$$$$33 from "./apps/blog/utils/handlePosts.ts";
import * as $$$$$$$$$$$29 from "./apps/blog/utils/Icon.tsx";
import * as $$$$$$$$$$$34 from "./apps/blog/utils/preview.tsx";
import * as $$$$$$$$$$$35 from "./apps/blog/utils/records.ts";
import * as $$$$$$$$$$$30 from "./apps/blog/utils/Slider.tsx";
import * as $$$$$$$$$$$36 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$37 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$38 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$39 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$40 from "./apps/site.ts";
import * as $$$0 from "./loaders/availableIcons.ts";
import * as $$$1 from "./loaders/icons.ts";
import * as $$$2 from "./loaders/minicart.ts";
import * as $$$3 from "./loaders/user.ts";
import * as $$$4 from "./loaders/wishlist.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Banner/BannerZoom.tsx";
import * as $$$$$$2 from "./sections/Banner/DoubleBanner.tsx";
import * as $$$$$$3 from "./sections/Banner/FullBanner.tsx";
import * as $$$$$$4 from "./sections/Banner/MiddleBanner.tsx";
import * as $$$$$$5 from "./sections/Banner/StickyBanner.tsx";
import * as $$$$$$6 from "./sections/BrandsCarousel/BrandsCarousel.tsx";
import * as $$$$$$7 from "./sections/BretonVersatilityCarousel/BretonVersatilityCarousel.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$10 from "./sections/Component.tsx";
import * as $$$$$$11 from "./sections/Content/Faq.tsx";
import * as $$$$$$12 from "./sections/Content/Hero.tsx";
import * as $$$$$$13 from "./sections/Content/Intro.tsx";
import * as $$$$$$14 from "./sections/Content/Logos.tsx";
import * as $$$$$$15 from "./sections/Designer/DesignerProductList.tsx";
import * as $$$$$$16 from "./sections/Designer/DesignersList.tsx";
import * as $$$$$$17 from "./sections/Footer/Footer.tsx";
import * as $$$$$$18 from "./sections/Footer/FooterLanguageSelector.tsx";
import * as $$$$$$19 from "./sections/Footer/FooterNewsletter.tsx";
import * as $$$$$$20 from "./sections/Header/Header.tsx";
import * as $$$$$$21 from "./sections/Home/BannerDesigner/BannerDesigner.tsx";
import * as $$$$$$22 from "./sections/Home/BulletPoints.tsx";
import * as $$$$$$23 from "./sections/Home/Ecobreton/Ecobreton.tsx";
import * as $$$$$$24 from "./sections/Iframe/ProxyIframe.tsx";
import * as $$$$$$25 from "./sections/Images/Banner.tsx";
import * as $$$$$$26 from "./sections/Images/Carousel.tsx";
import * as $$$$$$27 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$28 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$29 from "./sections/Institutional/InstitutionalCarousel.tsx";
import * as $$$$$$30 from "./sections/Institutional/InstitutionalEnvironment.tsx";
import * as $$$$$$31 from "./sections/Institutional/InstitutionalFooterNavigator.tsx";
import * as $$$$$$32 from "./sections/Institutional/InstitutionalForm.tsx";
import * as $$$$$$33 from "./sections/Institutional/InstitutionalInfoHighlight.tsx";
import * as $$$$$$34 from "./sections/Institutional/InstitutionalOrdenatedList.tsx";
import * as $$$$$$35 from "./sections/Institutional/InstitutionalOurActions.tsx";
import * as $$$$$$36 from "./sections/Institutional/InstitutionalPDF.tsx";
import * as $$$$$$37 from "./sections/Institutional/InstitutionalResponsabilities.tsx";
import * as $$$$$$38 from "./sections/Institutional/InstitutionalStores.tsx";
import * as $$$$$$39 from "./sections/Institutional/InstitutionalSustainability.tsx";
import * as $$$$$$40 from "./sections/Institutional/InstitutionalSustainableMaterials.tsx";
import * as $$$$$$41 from "./sections/Institutional/InstitutionalText.tsx";
import * as $$$$$$42 from "./sections/Institutional/InstitutionalTranslucid.tsx";
import * as $$$$$$43 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$44 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$45 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$46 from "./sections/ModalCookies/ModalCookies.tsx";
import * as $$$$$$47 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$48 from "./sections/Policies/Policies.tsx";
import * as $$$$$$49 from "./sections/Product/ProductDesigners.tsx";
import * as $$$$$$50 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$51 from "./sections/Product/ProductInfos.tsx";
import * as $$$$$$52 from "./sections/Product/ProductMainBanner.tsx";
import * as $$$$$$53 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$54 from "./sections/Product/ProductSlide.tsx";
import * as $$$$$$55 from "./sections/Product/ProductVideo.tsx";
import * as $$$$$$56 from "./sections/Product/RelatedProducts.tsx";
import * as $$$$$$57 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$58 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$59 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$60 from "./sections/Search/BannerCategory/BannerCategory.tsx";
import * as $$$$$$61 from "./sections/Search/RichText/SearchRichText.tsx";
import * as $$$$$$62 from "./sections/Search/SearchTerm/SearchTerm.tsx";
import * as $$$$$$63 from "./sections/Session.tsx";
import * as $$$$$$64 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$65 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$66 from "./sections/Spacer/Spacer.tsx";
import * as $$$$$$67 from "./sections/Theme/Theme.tsx";
import * as $$$$$$68 from "./sections/TimeLineCarousel/TimeLineCarousel.tsx";
import * as $$$$$$69 from "./sections/Video/Video.tsx";
import * as $$$$$$70 from "./sections/Video/VideoOrImage.tsx";

const manifest = {
  "loaders": {
    "site/loaders/availableIcons.ts": $$$0,
    "site/loaders/icons.ts": $$$1,
    "site/loaders/minicart.ts": $$$2,
    "site/loaders/user.ts": $$$3,
    "site/loaders/wishlist.ts": $$$4,
  },
  "sections": {
    "site/sections/Animation/Animation.tsx": $$$$$$0,
    "site/sections/Banner/BannerZoom.tsx": $$$$$$1,
    "site/sections/Banner/DoubleBanner.tsx": $$$$$$2,
    "site/sections/Banner/FullBanner.tsx": $$$$$$3,
    "site/sections/Banner/MiddleBanner.tsx": $$$$$$4,
    "site/sections/Banner/StickyBanner.tsx": $$$$$$5,
    "site/sections/BrandsCarousel/BrandsCarousel.tsx": $$$$$$6,
    "site/sections/BretonVersatilityCarousel/BretonVersatilityCarousel.tsx":
      $$$$$$7,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$8,
    "site/sections/Category/CategoryGrid.tsx": $$$$$$9,
    "site/sections/Component.tsx": $$$$$$10,
    "site/sections/Content/Faq.tsx": $$$$$$11,
    "site/sections/Content/Hero.tsx": $$$$$$12,
    "site/sections/Content/Intro.tsx": $$$$$$13,
    "site/sections/Content/Logos.tsx": $$$$$$14,
    "site/sections/Designer/DesignerProductList.tsx": $$$$$$15,
    "site/sections/Designer/DesignersList.tsx": $$$$$$16,
    "site/sections/Footer/Footer.tsx": $$$$$$17,
    "site/sections/Footer/FooterLanguageSelector.tsx": $$$$$$18,
    "site/sections/Footer/FooterNewsletter.tsx": $$$$$$19,
    "site/sections/Header/Header.tsx": $$$$$$20,
    "site/sections/Home/BannerDesigner/BannerDesigner.tsx": $$$$$$21,
    "site/sections/Home/BulletPoints.tsx": $$$$$$22,
    "site/sections/Home/Ecobreton/Ecobreton.tsx": $$$$$$23,
    "site/sections/Iframe/ProxyIframe.tsx": $$$$$$24,
    "site/sections/Images/Banner.tsx": $$$$$$25,
    "site/sections/Images/Carousel.tsx": $$$$$$26,
    "site/sections/Images/ImageGallery.tsx": $$$$$$27,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$28,
    "site/sections/Institutional/InstitutionalCarousel.tsx": $$$$$$29,
    "site/sections/Institutional/InstitutionalEnvironment.tsx": $$$$$$30,
    "site/sections/Institutional/InstitutionalFooterNavigator.tsx": $$$$$$31,
    "site/sections/Institutional/InstitutionalForm.tsx": $$$$$$32,
    "site/sections/Institutional/InstitutionalInfoHighlight.tsx": $$$$$$33,
    "site/sections/Institutional/InstitutionalOrdenatedList.tsx": $$$$$$34,
    "site/sections/Institutional/InstitutionalOurActions.tsx": $$$$$$35,
    "site/sections/Institutional/InstitutionalPDF.tsx": $$$$$$36,
    "site/sections/Institutional/InstitutionalResponsabilities.tsx": $$$$$$37,
    "site/sections/Institutional/InstitutionalStores.tsx": $$$$$$38,
    "site/sections/Institutional/InstitutionalSustainability.tsx": $$$$$$39,
    "site/sections/Institutional/InstitutionalSustainableMaterials.tsx":
      $$$$$$40,
    "site/sections/Institutional/InstitutionalText.tsx": $$$$$$41,
    "site/sections/Institutional/InstitutionalTranslucid.tsx": $$$$$$42,
    "site/sections/Links/LinkTree.tsx": $$$$$$43,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$44,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$45,
    "site/sections/ModalCookies/ModalCookies.tsx": $$$$$$46,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$47,
    "site/sections/Policies/Policies.tsx": $$$$$$48,
    "site/sections/Product/ProductDesigners.tsx": $$$$$$49,
    "site/sections/Product/ProductDetails.tsx": $$$$$$50,
    "site/sections/Product/ProductInfos.tsx": $$$$$$51,
    "site/sections/Product/ProductMainBanner.tsx": $$$$$$52,
    "site/sections/Product/ProductShelf.tsx": $$$$$$53,
    "site/sections/Product/ProductSlide.tsx": $$$$$$54,
    "site/sections/Product/ProductVideo.tsx": $$$$$$55,
    "site/sections/Product/RelatedProducts.tsx": $$$$$$56,
    "site/sections/Product/SearchResult.tsx": $$$$$$57,
    "site/sections/Product/ShelfWithImage.tsx": $$$$$$58,
    "site/sections/Product/Wishlist.tsx": $$$$$$59,
    "site/sections/Search/BannerCategory/BannerCategory.tsx": $$$$$$60,
    "site/sections/Search/RichText/SearchRichText.tsx": $$$$$$61,
    "site/sections/Search/SearchTerm/SearchTerm.tsx": $$$$$$62,
    "site/sections/Session.tsx": $$$$$$63,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$64,
    "site/sections/Social/WhatsApp.tsx": $$$$$$65,
    "site/sections/Spacer/Spacer.tsx": $$$$$$66,
    "site/sections/Theme/Theme.tsx": $$$$$$67,
    "site/sections/TimeLineCarousel/TimeLineCarousel.tsx": $$$$$$68,
    "site/sections/Video/Video.tsx": $$$$$$69,
    "site/sections/Video/VideoOrImage.tsx": $$$$$$70,
  },
  "actions": {
    "site/actions/minicart/submit.ts": $$$$$$$$$0,
    "site/actions/newsletter/subscribe.ts": $$$$$$$$$1,
    "site/actions/wishlist/submit.ts": $$$$$$$$$2,
  },
  "apps": {
    "site/apps/blog/islands/BackButton.tsx": $$$$$$$$$$$0,
    "site/apps/blog/loaders/Author.ts": $$$$$$$$$$$1,
    "site/apps/blog/loaders/Blogpost.ts": $$$$$$$$$$$5,
    "site/apps/blog/loaders/BlogPostItem.ts": $$$$$$$$$$$2,
    "site/apps/blog/loaders/BlogpostList.ts": $$$$$$$$$$$6,
    "site/apps/blog/loaders/BlogpostListing.ts": $$$$$$$$$$$7,
    "site/apps/blog/loaders/BlogPostPage.ts": $$$$$$$$$$$3,
    "site/apps/blog/loaders/BlogRelatedPosts.ts": $$$$$$$$$$$4,
    "site/apps/blog/loaders/Category.ts": $$$$$$$$$$$8,
    "site/apps/blog/loaders/ContentTypes.ts": $$$$$$$$$$$9,
    "site/apps/blog/loaders/GetCategories.ts": $$$$$$$$$$$10,
    "site/apps/blog/manifest.gen.ts": $$$$$$$$$$$11,
    "site/apps/blog/mod.ts": $$$$$$$$$$$12,
    "site/apps/blog/sections/Blog/components/ImageAndTextSection.tsx":
      $$$$$$$$$$$13,
    "site/apps/blog/sections/Blog/components/ImagesSlide.tsx": $$$$$$$$$$$16,
    "site/apps/blog/sections/Blog/components/ImageThreeColumnSection.tsx":
      $$$$$$$$$$$14,
    "site/apps/blog/sections/Blog/components/ImageTwoColumnSection.tsx":
      $$$$$$$$$$$15,
    "site/apps/blog/sections/Blog/components/OneImage.tsx": $$$$$$$$$$$17,
    "site/apps/blog/sections/Blog/components/ProductsSection.tsx":
      $$$$$$$$$$$18,
    "site/apps/blog/sections/Blog/components/RelatedPosts.tsx": $$$$$$$$$$$19,
    "site/apps/blog/sections/Blog/components/TextSection.tsx": $$$$$$$$$$$20,
    "site/apps/blog/sections/Blog/components/Video.tsx": $$$$$$$$$$$21,
    "site/apps/blog/sections/BlogBannerPost.tsx": $$$$$$$$$$$22,
    "site/apps/blog/sections/BlogPosts.tsx": $$$$$$$$$$$23,
    "site/apps/blog/sections/BlogTemplate.tsx": $$$$$$$$$$$24,
    "site/apps/blog/sections/Seo/SeoBlogPost.tsx": $$$$$$$$$$$25,
    "site/apps/blog/sections/Seo/SeoBlogPostListing.tsx": $$$$$$$$$$$26,
    "site/apps/blog/sections/Template.tsx": $$$$$$$$$$$27,
    "site/apps/blog/sections/types.ts": $$$$$$$$$$$28,
    "site/apps/blog/utils/clx.ts": $$$$$$$$$$$31,
    "site/apps/blog/utils/constants.ts": $$$$$$$$$$$32,
    "site/apps/blog/utils/handlePosts.ts": $$$$$$$$$$$33,
    "site/apps/blog/utils/Icon.tsx": $$$$$$$$$$$29,
    "site/apps/blog/utils/preview.tsx": $$$$$$$$$$$34,
    "site/apps/blog/utils/records.ts": $$$$$$$$$$$35,
    "site/apps/blog/utils/Slider.tsx": $$$$$$$$$$$30,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$36,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$37,
    "site/apps/deco/records.ts": $$$$$$$$$$$38,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$39,
    "site/apps/site.ts": $$$$$$$$$$$40,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
